In [2]:
pd.read_csv('DATA/solarenergy.csv')

C:\Users\bhara\AppData\Local\Temp\ipykernel_13128\321697996.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv('DATA/solarenergy.csv')

,Datetime,solar_mw,wind-direction,wind-speed,humidity,average-wind-speed-(period),average-pressure-(period),temperature
0,03/08/2020 0:00,11385,27,7.5,75.0,8.0,29.82,69.0
1,02/08/2020 23:00,12390,27,7.5,77.0,5.0,29.85,69.0
2,02/08/2020 22:00,13312,27,7.5,70.0,0.0,29.89,69.0
3,02/08/2020 21:00,13832,27,7.5,33.0,0.0,29.91,69.0
4,02/08/2020 20:00,14038,27,7.5,21.0,3.0,29.89,69.0
...,...,...,...,...,...,...,...,...
116112,01/05/2007 5:00,6445,NaN,NaN,NaN,NaN,NaN,NaN
116113,01/05/2007 4:00,6452,NaN,NaN,NaN,NaN,NaN,NaN
116114,01/05/2007 3:00,6583,NaN,NaN,NaN,NaN,NaN,NaN
116115,01/05/2007 2:00,6803,NaN,NaN,NaN,NaN,NaN,NaN
116116,01/05/2007 1:00,7190,NaN,NaN,NaN,NaN,NaN,NaN